/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file provides AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f411xe.h"
#include <stdint.h>

/*variables*/

/*Exercise 0.1*/
uint8_t my_variable = 0;

/*Exercise 0.2*/
uint8_t dec = 0;
uint8_t hex = 0;
uint8_t bin = 0;

/*Exercise 0.4*/
int8_t c = 0;

/*Exercise 0.6*/
uint8_t result = 0;  // ← corregido, le faltaba el tipo

/*Exercise 0.*/
uint8_t x = 0;

/*Exercise 1.1*/
uint8_t a = 17;
uint8_t b = 5;

/*Exercise 1.3*/
uint8_t val = 3;


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /*Exercise 0.1*/
    uint8_t my_variable = 42;

    /*Exercise 0.2*/
    uint8_t dec = 65;
    uint8_t hex = 0x41;
    uint8_t bin = 0b01000001;

    /*Exercise 0.4*/

    /*Exercise 0.6*/
    result = 0x0F + 0x01;  /* prediccion: 16  */
    result = 0xFF + 0x01;  /* prediccion: 0 (overflow uint8) */
    result = 0xA0 + 0x5F;  /* prediccion: 255 */
    result = 0xA0 + 0x60;  /* prediccion: 0 (overflow uint8) */

    /*Exercise 0.7*/
    x = 0x01;
    x = 0x02;
    x = 0x04;
    x = 0x08;
    x = 0x10;
    x = 0x20;
    x = 0x40;
    x = 0x80;

    /*Exercise 1.1*/
    uint8_t div_result = a / b;
    uint8_t mod_result = a % b;
    uint8_t mul_result = a * b;

    /*Exercise 1.3*/
    uint8_t left1 = val << 1;
    uint8_t left2 = val << 2;
    uint8_t left3 = val << 3;
    uint8_t right1 = val >> 1;






	/*clase 22 mayo*/
	GPIOA->MODER;    // autocompleta bien




	/*clase 29 configuraciion TIM3*/


	RCC->APB1ENR &= ~(RCC_APB1ENR_TIM3EN);


	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;



	TIM3->PSC = (1600 -1);


	TIM3->ARR = (3250 -1);



	TIM3->CNT = 0;


	TIM3->SR &= ~(TIM_SR_UIF);



	TIM3->DIER &= ~(TIM_DIER_UIE);


	TIM3->DIER |= TIM_DIER_UIE;


	/* MATRICULANDO LA INTERRUPCION TIM3 EN EL NVIC, PARA QUE SEA RECONOCIDA*/
	__NVIC_EnableIRQ(TIM3_IRQn);



	/* CONFIGURACION DE LA DIRECCION EN LA QUE EL CONTADOR CUENTA*/

	TIM3->CR1 &= ~(TIM3_CR1_DIR);

	/*ACTIVAMOS PRECARGA DEL ARR*/


	TIM3->CR1 &= ~(TIM_CR1_ARPE);


	TIM3->CR1 |= TIM_CR1_ARPE;


	TIM3->CR1 |= TIM_CR1_CEN;






    /* Loop forever */
    while(1){}
}




/* FUNCION ISR PARA EL TIM3, TODA FUNCION ISR NO RRETORNA NADA (VOID)*/
void TIM3_IRQHandler(void){

	/*VERIFICAR QUE GENERO LA INTERUPCION*/
	if(TIM3->SR && TIM_SR_UIF){
		GPIOA->ODR ^= GPIO_ODR_OD5;



	}
}
